#!/usr/bin/env bash
set -x
PS4='+\t '
let dir="$1+30"
cd src/network/
ulimit -n 24096
for batch_size in {16..256..48}; do
	sleep 0s
	sleep 0s
	sleep 1s
done;
mkdir -p bws
for load in 1 5 10 15 20 24; do
        for batch_size in {16..256..48}; do
		sleep 19s
		./client < configs/$dir/"$load"G_consist_to_1.config &> client_logs/"$load"G-3-"$batch_size"-1 &
		./client < configs/$dir/"$load"G_consist_to_2.config &> client_logs/"$load"G-3-"$batch_size"-2 &
		./client < configs/$dir/"$load"G_consist_to_3.config &> client_logs/"$load"G-3-"$batch_size"-3 &
		sleep "$dir"s
		sleep 1m
		for dest in 1 2 3; do
			mv bw-"$dest".txt bws/"$load"G-3-"$batch_size"-"$dest"
		done;
        done;
done;
for b in {16..256..48}; do for rate in 0 1 5 10 15 20 24; do for dest in 1 2 3; do python read_bw.py bws/"$rate"G-3-$b-"$dest" 0 >> "recap-3-bg-`date +%m-%d-%Y`"; done; done; done;
